### ISSUE TITLE
Curl Error in GuzzleHttp (Calendar API)

### ISSUE THREAD

**Issue by jazzsandhu** [gsuitedevs/php-samples#63]
(Please search [existing issues](https://github.com/gsuitedevs/php-samples/issues) before creating a new one.)

**Sample:**

## Expected Behavior
print the list of events form the calendar

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - PHP version (`php -7.2):
  - OS (Windows):

#11 
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in C:\MAMP\htdocs\API\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 67
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcur
l-errors.html) in C:\MAMP\htdocs\API\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187
Stack trace:
#0 C:\MAMP\htdocs\API\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\MAMP\htdocs\API\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Han
dler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\MAMP\htdocs\API\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\E
asyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 C:\MAMP\htdocs\API\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler in C:\MAMP\htdocs\API\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by sukhvir1313** [comment]
Having same issue since 17 April 2020, before that it was working properly:

Stack trace:
#0 /home/zoomext/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/zoomext/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/zoomext/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/zoomext/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleH in /home/zoomext/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
